# Numpy Array Indexing And Operations 

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[4]

4

In [60]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [61]:
slice_of_arr = arr[0:6]

In [62]:
slice_of_arr 

array([0, 1, 2, 3, 4, 5])

In [63]:
slice_of_arr[:] = 20

In [64]:
slice_of_arr

array([20, 20, 20, 20, 20, 20])

In [65]:
arr  # This means that numpy array does not make a copy of array automatically it just create the view of the original data

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10])

In [66]:
# after the copy of array will not affect the original array
copy_arr = arr.copy()

In [67]:
copy_arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10])

In [68]:
copy_arr[0:5] = 30

In [69]:
copy_arr

array([30, 30, 30, 30, 30, 20,  6,  7,  8,  9, 10])

In [70]:
arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10])

In [71]:
arr_2d = np.random.randint(0,5,9)

In [72]:
arr_2d

array([2, 3, 1, 0, 3, 4, 1, 0, 0])

In [73]:
arr_2d = arr_2d.reshape(3,3)

In [75]:
arr_2d

array([[2, 3, 1],
       [0, 3, 4],
       [1, 0, 0]])

In [78]:
arr_2d[1,2]

4

In [79]:
arr_2d[1,2]

4

In [80]:
arr_2d

array([[2, 3, 1],
       [0, 3, 4],
       [1, 0, 0]])

In [81]:
arr_2d[1:,:2]

array([[0, 3],
       [1, 0]])

In [82]:
arr_2d[:,1:]

array([[3, 1],
       [3, 4],
       [0, 0]])

In [83]:
bool_arr = np.arange(0,11)

In [84]:
bool_arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
bool_arr> 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [86]:
bool_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
bool_arr[bool_arr > 5]

array([ 6,  7,  8,  9, 10])

In [89]:
arr1 = np.arange(50).reshape(5,10)

In [91]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [92]:
arr1[1:3,5:7]

array([[15, 16],
       [25, 26]])

**Operations** 

In [95]:
samp_arr1 = np.array([20,3,56,11,4])

In [97]:
samp_arr1

array([20,  3, 56, 11,  4])

In [98]:
samp_arr2 = np.array([22,98,14,4,67])

In [99]:
samp_arr2

array([22, 98, 14,  4, 67])

In [100]:
samp_arr1 + samp_arr2

array([ 42, 101,  70,  15,  71])

In [40]:
samp_arr1 * samp_arr2

array([440, 294, 784,  44, 268])

In [41]:
samp_arr1 *2

array([ 40,   6, 112,  22,   8])

In [42]:
samp_arr1

array([20,  3, 56, 11,  4])

In [43]:
samp_arr1[1:3] + 3

array([ 6, 59])

In [44]:
np.sqrt(samp_arr1)

array([4.47213595, 1.73205081, 7.48331477, 3.31662479, 2.        ])

In [45]:
np.exp(samp_arr2)

array([3.58491285e+09, 3.63797095e+42, 1.20260428e+06, 5.45981500e+01,
       1.25236317e+29])

In [46]:
np.max(samp_arr1)

56

In [47]:
samp_arr1.argmax()

2

In [48]:
np.sin(samp_arr2)

array([-0.00885131, -0.57338187,  0.99060736, -0.7568025 , -0.85551998])